"""Phase 3 domain model: storage-agnostic product entities and ownership metadata."""

from app.domain.connectors import ConnectorInstance, ConnectorTemplate
from app.domain.jobs import (
    JobDefinition,
    PipelineDefinition,
    StageDefinition,
    StepInstance,
    StepTemplate,
)
from app.domain.limits import AppLimits
from app.domain.ownership import Visibility
from app.domain.repositories import (
    AppConfigRepository,
    ConnectorInstanceRepository,
    ConnectorTemplateRepository,
    JobRepository,
    RunRepository,
    StepTemplateRepository,
    TargetRepository,
    TargetSchemaRepository,
    TargetTemplateRepository,
    TriggerRepository,
)
from app.domain.runs import JobRun, PipelineRun, StageRun, StepRun, UsageRecord
from app.domain.targets import (
    DataTarget,
    TargetSchemaProperty,
    TargetSchemaSnapshot,
    TargetTemplate,
)
from app.domain.triggers import TriggerDefinition
from app.domain.yaml_layout import (
    BOOTSTRAP_JOBS,
    CATALOG_CONNECTOR_TEMPLATES,
    CATALOG_STEP_TEMPLATES,
    CATALOG_TARGET_TEMPLATES,
    PRODUCT_MODEL_ROOT,
    TENANT_APP_CONFIG,
    TENANT_CONNECTOR_INSTANCES,
    TENANT_JOBS,
    TENANT_RUNS,
    TENANT_TARGETS,
    TENANT_TARGET_SCHEMA_SNAPSHOTS,
    TENANT_TRIGGERS,
    bootstrap_job_path,
    catalog_connector_template_path,
    catalog_step_template_path,
    catalog_target_template_path,
    tenant_app_config_path,
    tenant_connector_instances_dir,
    tenant_jobs_dir,
    tenant_root,
    tenant_runs_dir,
    tenant_targets_dir,
    tenant_target_schema_snapshots_dir,
    tenant_triggers_dir,
)

__all__ = [
    "AppConfigRepository",
    "AppLimits",
    "BOOTSTRAP_JOBS",
    "CATALOG_CONNECTOR_TEMPLATES",
    "CATALOG_STEP_TEMPLATES",
    "CATALOG_TARGET_TEMPLATES",
    "ConnectorInstance",
    "ConnectorInstanceRepository",
    "ConnectorTemplate",
    "ConnectorTemplateRepository",
    "DataTarget",
    "JobDefinition",
    "JobRepository",
    "JobRun",
    "PipelineDefinition",
    "PipelineRun",
    "PRODUCT_MODEL_ROOT",
    "RunRepository",
    "StageDefinition",
    "StageRun",
    "StepInstance",
    "StepRun",
    "StepTemplate",
    "StepTemplateRepository",
    "TENANT_APP_CONFIG",
    "TENANT_CONNECTOR_INSTANCES",
    "TENANT_JOBS",
    "TENANT_RUNS",
    "TENANT_TARGETS",
    "TENANT_TARGET_SCHEMA_SNAPSHOTS",
    "TENANT_TRIGGERS",
    "TargetRepository",
    "TargetSchemaProperty",
    "TargetSchemaRepository",
    "TargetSchemaSnapshot",
    "TargetTemplate",
    "TargetTemplateRepository",
    "TriggerDefinition",
    "TriggerRepository",
    "UsageRecord",
    "Visibility",
    "bootstrap_job_path",
    "catalog_connector_template_path",
    "catalog_step_template_path",
    "catalog_target_template_path",
    "tenant_app_config_path",
    "tenant_connector_instances_dir",
    "tenant_jobs_dir",
    "tenant_root",
    "tenant_runs_dir",
    "tenant_targets_dir",
    "tenant_target_schema_snapshots_dir",
    "tenant_triggers_dir",
]
